name: Daily Horoscope Update

on:
  schedule:
    - cron: '0 6 * * *'  # every day at 6 AM UTC
  workflow_dispatch:  # allow manual trigger too

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run app1.py
        run: python app1.py

      - name: Commit and Push JSON updates
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add public/*.json
          git commit -m "Daily auto update" || echo "No changes to commit"
          git push
