name: Daily Horoscope Update
permissions:
  contents: write

on:
  schedule:
    - cron: "30 3 * * *"  # Runs daily at 9:00 AM IST
  workflow_dispatch:

permissions:
  contents: write  # ✅ Required for git push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # ✅ We'll use our own token
          submodules: false           # ✅ Avoid submodule issues

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "RAPIDAPI_KEY=${{ secrets.RAPIDAPI_KEY }}" >> $GITHUB_ENV
          echo "RAPIDAPI_HOST=${{ secrets.RAPIDAPI_HOST }}" >> $GITHUB_ENV
          echo "DEEPINFRA_API_KEY=${{ secrets.DEEPINFRA_API_KEY }}" >> $GITHUB_ENV

      - name: Run app1.py
        run: python app1.py

      - name: Configure Git and Push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # ✅ Your Personal Access Token
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add frontend/public/*.json
          git commit -m "Daily auto update" || echo "No changes to commit"
          git push origin main
